// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	MessageResponse
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Message) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MessageResponse struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *MessageResponse) Reset()                    { *m = MessageResponse{} }
func (m *MessageResponse) String() string            { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()               {}
func (*MessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MessageResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "grpc.Message")
	proto.RegisterType((*MessageResponse)(nil), "grpc.MessageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for C service

type CClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc1.CallOption) (*MessageResponse, error)
}

type cClient struct {
	cc *grpc1.ClientConn
}

func NewCClient(cc *grpc1.ClientConn) CClient {
	return &cClient{cc}
}

func (c *cClient) SendMessage(ctx context.Context, in *Message, opts ...grpc1.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := grpc1.Invoke(ctx, "/grpc.c/SendMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for C service

type CServer interface {
	SendMessage(context.Context, *Message) (*MessageResponse, error)
}

func RegisterCServer(s *grpc1.Server, srv CServer) {
	s.RegisterService(&_C_serviceDesc, srv)
}

func _C_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CServer).SendMessage(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.c/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _C_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.c",
	HandlerType: (*CServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _C_SendMessage_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56,
	0x32, 0xe4, 0x62, 0xf7, 0x85, 0x08, 0x0b, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12,
	0x4c, 0x60, 0x31, 0x08, 0x47, 0x49, 0x9b, 0x8b, 0x1f, 0xaa, 0x25, 0x28, 0xb5, 0xb8, 0x20, 0x3f,
	0xaf, 0x38, 0x55, 0x48, 0x82, 0x8b, 0x3d, 0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x04, 0xaa, 0x1d,
	0xc6, 0x35, 0xb2, 0xe2, 0x62, 0x4c, 0x16, 0x32, 0xe5, 0xe2, 0x0e, 0x4e, 0xcd, 0x4b, 0x81, 0x59,
	0xc4, 0xab, 0x07, 0xb2, 0x5a, 0x0f, 0xca, 0x95, 0x12, 0x45, 0xe1, 0xc2, 0xcc, 0x54, 0x62, 0x48,
	0x62, 0x03, 0x3b, 0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x18, 0x1d, 0x33, 0x08, 0xb9, 0x00,
	0x00, 0x00,
}
